---
# tasks file for update_kernel
- name: upgrade all packages
  yum: name=* state=latest
  when: ansible_pkg_mgr == 'yum'

- name: Check for reboot hint.
  shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint
  when: ansible_pkg_mgr == 'yum'
  changed_when: reboot_hint.stdout.find("reboot") != -1
  notify: 'restart server'

- name: Update all packages on a Debian/Ubuntu
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_pkg_mgr == 'apt'

- name: Copy sshd_config file
  template: src={{ role_path }}/templates/sshd_config.j2 dest="/etc/ssh/sshd_config"
  notify: restart sshd
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Reboot if necessary on Debian/Ubuntu'
  stat:
    path: /var/run/reboot-required
  register: result
  changed_when: result.stat.exists
  notify: 'restart server'
  when: ansible_pkg_mgr == 'apt'

- name: Create VolumeGroup
  lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ device_name }}"

- name: Create new LVM partition
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lvm_name }}"
    size: 80%VG

- name: Create filesystem for LVM
  filesystem:
    fstype: xfs
    dev: "/dev/{{ vg_name }}/{{ lvm_name }}"

- name: Mount the LVM partiton
  mount:
    name: /apps/testing
    src: "/dev/{{ vg_name }}/{{ lvm_name }}"
    fstype: xfs
    state: mounted

- name: disable IPv6
  template:
    src: disableipv6.conf.j2
    dest: /etc/sysctl.d/10-disable-ipv6.conf
  notify: 'run sysctl'
